// CloudCoder - a web-based pedagogical programming environment
// Copyright (C) 2011-2012, Jaime Spacco <jspacco@knox.edu>
// Copyright (C) 2011-2012, David H. Hovemeyer <david.hovemeyer@gmail.com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

package org.cloudcoder.app.shared.model;

/**
 * Types of indices that correspond to model object fields.
 * These define semantics of model objects persistence (for example,
 * a field with a UNIQUE index specifies that no two distinct model objects
 * may have the same value for that field), and also suggest patterns
 * of access that may be optimized (for example, a field with
 * a NON_UNIQUE index suggests that searches on that field will
 * be done frequently). 
 * 
 * @author David Hovemeyer
 */
public enum ModelObjectIndexType {
	/**
	 * Specifies that no index is needed for this field.
	 */
	NONE,
	
	/**
	 * Specifies that a field is the unique id for the object,
	 * and that the field value will be automatically generated by
	 * the persistent store (e.g., it will be an autoincrement
	 * database column).
	 */
	IDENTITY,
	
	/**
	 * Specifies that no two distinct model objects may share the same
	 * value for the field. 
	 */
	UNIQUE,
	
	/**
	 * Specifies that searches will be done to identify
	 * model objects with a particular field value, but that multiple
	 * distinct model objects may share the same field value.
	 */
	NON_UNIQUE,
}
